version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
    env_file:
      - backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

  cypress:
    image: cypress/included:13.6.3
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:4200
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
      - ./cypress/tsconfig.json:/e2e/tsconfig.json
    command: ["cypress", "run", "--config-file", "cypress.config.js"]