name: CI Pipeline

on:
  push:
    branches: [ main, feature/iba-final-architecture ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Lint and Format Check (Ruff)
      run: |
        pip install ruff
        cd backend
        ruff check .
        ruff format --check .
    - name: Run backend tests
      run: |
        cd backend
        pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linting
      run: npm run lint
    - name: Build application
      run: npm run build
    - name: Run tests
      # This project does not have a test runner configured. 
      # This step is a placeholder.
      run: echo "Skipping frontend tests"